version: "3.9"

services:
  "web-server":
    image: "nginx:alpine"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-api
    volumes:
      - ~/Documents/Repos/nginx_conf:/etc/nginx/conf.d
  "web-api":
    image: "web-api"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      AppConfigurationConnectionString: ${AppConfigurationConnectionString}
    build:
      context: .
      dockerfile: src/WoodenWorkshop.PublicApi.Web/Dockerfile
  users:
    image: "users"
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      AppConfigurationConnectionString: ${AppConfigurationConnectionString}
    build:
      context: .
      dockerfile: src/WoodenWorkshop.Users.Api/Dockerfile
  passwords:
    image: "passwords"
    ports:
      - "8001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      AppConfigurationConnectionString: ${AppConfigurationConnectionString}
    build:
      context: .
      dockerfile: src/WoodenWorkshop.Passwords.Api/Dockerfile
  "invitations":
    image: "invitations"
    ports:
      - "8002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      AppConfigurationConnectionString: ${AppConfigurationConnectionString}
    build:
        context: .
        dockerfile: src/WoodenWorkshop.Invitations.Api/Dockerfile
  mailing:
    image: "mailing"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      AppConfigurationConnectionString: ${AppConfigurationConnectionString}
    ports:
      - "8003:80"
    build:
      context: .
      dockerfile: src/WoodenWorkshop.Mailing.Api/Dockerfile
    depends_on:
      - queue
  sessions:
    image: "sessions"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      AppConfigurationConnectionString: ${AppConfigurationConnectionString}
    ports:
      - "8004:80"
    build:
      context: .
      dockerfile: src/WoodenWorkshop.Sessions.Api/Dockerfile
  queue:
    hostname: "queue"
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq123"
    volumes:
      - queue-storage:/var/lib/rabbitmq
      - queue-storage:/var/log/rabbitmq
    ports:
      - "9000:15672"
      - "9001:5762"

volumes:
  queue-storage:
