version: "3.9"

services:
  users:
    image: "users"
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      AppConfigurationConnectionString: ${AppConfigurationConnectionString}
    build:
      context: .
      dockerfile: src/WoodenWorkshop.Users.Api/Dockerfile
